### ISSUE TITLE
Remote Path is required

### ISSUE THREAD

**Issue by istairbn** [xebialabs-community/xlr-powershell-plugin#4]
If you don't provide a Remote Path, you get the following error.
Is it possible to make RemotePath a required variable for this task type rather than optional?

Script failed. call to powershell object
Exit code 
1

#### Error stream:
java.lang.NullPointerException
	at com.xebialabs.overthere.cifs.PathEncoder.toSmbUrl(PathEncoder.java:78)
	at com.xebialabs.overthere.cifs.CifsConnection.encodeAsSmbUrl(CifsConnection.java:144)
	at com.xebialabs.overthere.cifs.CifsConnection.getFile(CifsConnection.java:119)
	at com.xebialabs.xlrelease.plugin.overthere.PowershellScript.execute(PowershellScript.java:51)
	at sun.reflect.GeneratedMethodAccessor274.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:186)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204)
	at org.python.core.PyObject.__call__(PyObject.java:461)
	at org.python.core.PyObject.__call__(PyObject.java:465)
	at org.python.core.PyMethod.__call__(PyMethod.java:126)
	at org.python.pycode._pyx953.f$0(<script>:31)
	at org.python.pycode._pyx953.call_function(<script>)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.core.__builtin__.eval(__builtin__.java:497)
	at org.python.core.__builtin__.eval(__builtin__.java:501)
	at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:259)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:40)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
	at com.xebialabs.xlrelease.script.Jsr223ScriptExecutor.lambda$evalScriptPrivileged$148(Jsr223ScriptExecutor.java:55)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.xebialabs.xlrelease.script.Jsr223ScriptExecutor.evalScriptPrivileged(Jsr223ScriptExecutor.java:55)
	at com.xebialabs.xlrelease.script.jython.JythonScriptExecutor.evalScriptWithUtilities(JythonScriptExecutor.java:60)
	at com.xebialabs.xlrelease.script.jython.JythonScriptExecutor.evalScriptWithApi(JythonScriptExecutor.java:49)
	at com.xebialabs.xlrelease.script.DefaultScriptService.executeScript(DefaultScriptService.java:650)
	at com.xebialabs.xlrelease.script.DefaultScriptService.lambda$executeCustomScriptTask$135(DefaultScriptService.java:205)
	at com.xebialabs.deployit.plumbing.scheduler.Scheduler.lambda$withLoggedExceptions$23(Scheduler.java:101)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

----
Exception during execution:
SystemExit: 1 in <script> at line number 31

**Comment by jdewinne** [comment]
Changed this in [v1.1.0](https://github.com/xebialabs-community/xlr-powershell-plugin/releases/tag/v1.1.0)
